"""create_questionnaire_tables

Revision ID: 89c2c3c1adbf
Revises: 973bf4887da1
Create Date: 2026-08-31 01:27:12.154408

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89c2c3c1adbf'
down_revision: Union[str, None] = '973bf4887da1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('questionnaire_questions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('question_code', sa.String(length=50), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('question_type', sa.Enum('BOOLEAN', 'SINGLE_CHOICE', 'MULTI_CHOICE', 'NUMBER', 'TEXT', name='questiontype', native_enum=False), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('options', sa.JSON(), nullable=False),
    sa.Column('branching_rules', sa.JSON(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_questionnaire_questions_question_code'), 'questionnaire_questions', ['question_code'], unique=True)
    op.create_table('questionnaire_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('patient_id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('IN_PROGRESS', 'COMPLETED', 'ABANDONED', name='sessionstatus', native_enum=False), nullable=False),
    sa.Column('current_question_code', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patient_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_questionnaire_sessions_patient_id'), 'questionnaire_sessions', ['patient_id'], unique=False)
    op.create_index(op.f('ix_questionnaire_sessions_status'), 'questionnaire_sessions', ['status'], unique=False)
    op.create_table('questionnaire_answers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('question_id', sa.String(length=36), nullable=False),
    sa.Column('question_code', sa.String(length=50), nullable=False),
    sa.Column('answer', sa.JSON(), nullable=False),
    sa.Column('answered_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questionnaire_questions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['questionnaire_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_questionnaire_answers_question_code'), 'questionnaire_answers', ['question_code'], unique=False)
    op.create_index(op.f('ix_questionnaire_answers_question_id'), 'questionnaire_answers', ['question_id'], unique=False)
    op.create_index(op.f('ix_questionnaire_answers_session_id'), 'questionnaire_answers', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_questionnaire_answers_session_id'), table_name='questionnaire_answers')
    op.drop_index(op.f('ix_questionnaire_answers_question_id'), table_name='questionnaire_answers')
    op.drop_index(op.f('ix_questionnaire_answers_question_code'), table_name='questionnaire_answers')
    op.drop_table('questionnaire_answers')
    op.drop_index(op.f('ix_questionnaire_sessions_status'), table_name='questionnaire_sessions')
    op.drop_index(op.f('ix_questionnaire_sessions_patient_id'), table_name='questionnaire_sessions')
    op.drop_table('questionnaire_sessions')
    op.drop_index(op.f('ix_questionnaire_questions_question_code'), table_name='questionnaire_questions')
    op.drop_table('questionnaire_questions')
    # ### end Alembic commands ###

