"""create_daily_health_checks_table

Revision ID: 973bf4887da1
Revises: f4d6b09b5cf3
Create Date: 2026-08-31 01:23:47.973913

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '973bf4887da1'
down_revision: Union[str, None] = 'f4d6b09b5cf3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_health_checks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('patient_id', sa.String(length=36), nullable=False),
    sa.Column('check_date', sa.Date(), nullable=False),
    sa.Column('dizziness_severity', sa.Integer(), nullable=False),
    sa.Column('episode_duration', sa.String(length=100), nullable=False),
    sa.Column('imbalance_severity', sa.Integer(), nullable=False),
    sa.Column('nausea', sa.Boolean(), nullable=False),
    sa.Column('headache', sa.Boolean(), nullable=False),
    sa.Column('sleep_hours', sa.Float(), nullable=False),
    sa.Column('hydration_level', sa.String(length=50), nullable=False),
    sa.Column('stress_level', sa.Integer(), nullable=False),
    sa.Column('medication_adherence', sa.String(length=100), nullable=False),
    sa.Column('triggers', sa.JSON(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patient_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('patient_id', 'check_date', name='uq_patient_daily_health_check')
    )
    op.create_index(op.f('ix_daily_health_checks_check_date'), 'daily_health_checks', ['check_date'], unique=False)
    op.create_index(op.f('ix_daily_health_checks_patient_id'), 'daily_health_checks', ['patient_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_daily_health_checks_patient_id'), table_name='daily_health_checks')
    op.drop_index(op.f('ix_daily_health_checks_check_date'), table_name='daily_health_checks')
    op.drop_table('daily_health_checks')
    # ### end Alembic commands ###

