"""create_doctor_notes_table

Revision ID: aa57239e9162
Revises: 7262081e3b85
Create Date: 2026-08-31 01:49:54.907505

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa57239e9162'
down_revision: Union[str, None] = '7262081e3b85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doctor_notes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('patient_id', sa.String(length=36), nullable=False),
    sa.Column('doctor_id', sa.String(length=36), nullable=False),
    sa.Column('risk_assessment_id', sa.String(length=36), nullable=True),
    sa.Column('note_type', sa.Enum('ROUTINE_REVIEW', 'EMERGENCY_FOLLOW_UP', 'DIAGNOSTIC_HYPOTHESIS', 'DISCHARGE', name='notetype', native_enum=False), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_shared_with_patient', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctor_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patient_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['risk_assessment_id'], ['risk_assessments.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_doctor_notes_doctor_id'), 'doctor_notes', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_doctor_notes_patient_id'), 'doctor_notes', ['patient_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_doctor_notes_patient_id'), table_name='doctor_notes')
    op.drop_index(op.f('ix_doctor_notes_doctor_id'), table_name='doctor_notes')
    op.drop_table('doctor_notes')
    # ### end Alembic commands ###

