"""create_eye_analysis_tables

Revision ID: afe373a21a4b
Revises: 89c2c3c1adbf
Create Date: 2026-08-31 01:33:14.398201

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'afe373a21a4b'
down_revision: Union[str, None] = '89c2c3c1adbf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('eye_analysis_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('patient_id', sa.String(length=36), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('analysis_status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'INSUFFICIENT_QUALITY', 'CANCELLED', name='eyeanalysisstatus', native_enum=False), nullable=False),
    sa.Column('quality_summary', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patient_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_eye_analysis_sessions_analysis_status'), 'eye_analysis_sessions', ['analysis_status'], unique=False)
    op.create_index(op.f('ix_eye_analysis_sessions_patient_id'), 'eye_analysis_sessions', ['patient_id'], unique=False)
    op.create_table('eye_movement_features',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('feature_name', sa.String(length=100), nullable=False),
    sa.Column('feature_value', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['eye_analysis_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_eye_movement_features_feature_name'), 'eye_movement_features', ['feature_name'], unique=False)
    op.create_index(op.f('ix_eye_movement_features_session_id'), 'eye_movement_features', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_eye_movement_features_session_id'), table_name='eye_movement_features')
    op.drop_index(op.f('ix_eye_movement_features_feature_name'), table_name='eye_movement_features')
    op.drop_table('eye_movement_features')
    op.drop_index(op.f('ix_eye_analysis_sessions_patient_id'), table_name='eye_analysis_sessions')
    op.drop_index(op.f('ix_eye_analysis_sessions_analysis_status'), table_name='eye_analysis_sessions')
    op.drop_table('eye_analysis_sessions')
    # ### end Alembic commands ###

